allowBuilds:
  sqlite3: true
  zeromq: true
minimumReleaseAgeExclude:
  - cookie@0.7.0
  - "@sveltejs/kit@2.61.0"
  - "@threlte/core@8.5.15"
  - "@threlte/extras@9.20.0"
overrides:
  cookie@<0.7.0: ^0.7.0
